spring.application.name=comparador-produtos


spring.datasource.url=jdbc:mysql://localhost:3306/comparador
spring.datasource.username=root
spring.datasource.password=Florestanegra77.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true